<a href="https://colab.research.google.com/github/PJHSE/Learning/blob/main/20200205.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
pip install tensorflow

In [53]:
import tensorflow as tf 
tf.__version__

'2.7.0'

In [ ]:
pip install keras

In [4]:
import keras
keras.__version__

'2.7.0'

In [5]:
pip install gensim

In [6]:
import gensim 
gensim.__version__

'3.6.0'

In [ ]:
pip install scikit-learn

In [8]:
import sklearn
sklearn.__version__

'1.0.2'

In [9]:
import nltk
nltk.__version__

'3.2.5'

In [ ]:
pip install konlpy

In [11]:
import konlpy
konlpy.__version__

'0.6.0'

In [12]:
import pandas as pd

In [13]:
sr = pd.Series([35000, 25000, 10000, 5000],index=['R석', 'S석', '일반석', '입석'])

print('표의 가격 :')
print('-'*20)
print(sr)

표의 가격 :
--------------------
R석     35000
S석     25000
일반석    10000
입석      5000
dtype: int64


In [14]:
print('표의 값(가격) :{}'.format(sr.values))
print('표의 종류(인덱스) :{}'.format(sr.index))

표의 값(가격) :[35000 25000 10000  5000]
표의 종류(인덱스) :Index(['R석', 'S석', '일반석', '입석'], dtype='object')


In [15]:
values = [[23.7, 12.2, 1.5],[13.9, 8.7, 7.5],[15.3, 5.0, 9.7] ]
index = ['orhodox center', 'point forward', 'Reading guard']
column = ['avp', 'avr', 'ava']

df = pd.DataFrame(values, index=index, columns=column)

print('3 선수의 평균 성적 : ')
print('-' *20)
print(df)

3 선수의 평균 성적 : 
--------------------
                 avp   avr  ava
orhodox center  23.7  12.2  1.5
point forward   13.9   8.7  7.5
Reading guard   15.3   5.0  9.7


In [16]:
print('3 선수의 포지션 : {}'.format(df.index))
print('3 선수가 갖는 3개의 지표 : {}'.format(df.columns))

3 선수의 포지션 : Index(['orhodox center', 'point forward', 'Reading guard'], dtype='object')
3 선수가 갖는 3개의 지표 : Index(['avp', 'avr', 'ava'], dtype='object')


In [17]:
data = [[23, 'Davis', 13.2],[30, 'Curry', 16.8], [1, 'Embiid', 16.5], [6, 'James', 14.9]]
df = pd.DataFrame(data)
print(df)

    0       1     2
0  23   Davis  13.2
1  30   Curry  16.8
2   1  Embiid  16.5
3   6   James  14.9


In [18]:
df=pd.DataFrame(data, columns = ['등번호','이름','승리 기여도' ], index = ['PowerForward', 'Point Guard', 'Center', 'Small Forward'])
#df=pd.DataFrame(data, index = ['PowerForward', 'Point Guard', 'Center', 'Small Forward'])

In [19]:
print(df)

               등번호      이름  승리 기여도
PowerForward    23   Davis    13.2
Point Guard     30   Curry    16.8
Center           1  Embiid    16.5
Small Forward    6   James    14.9


In [20]:
data = {'등번호' : ['23', '30', '1', '6'],'이름':['Davis','Curry', 'Embiid', 'James'], '승리 기여도':[13.2, 16.8, 16.5, 14.9] }
df=pd.DataFrame(data)
print(df)

  등번호      이름  승리 기여도
0  23   Davis    13.2
1  30   Curry    16.8
2   1  Embiid    16.5
3   6   James    14.9


In [21]:
df.head(1)

등번호     이름  승리 기여도
0  23  Davis    13.2

In [22]:
df['등번호']

0    23
1    30
2     1
3     6
Name: 등번호, dtype: object

In [23]:
import numpy as np

In [24]:
list = np.array([1, 2, 3, 4, 5])

In [25]:
print(list)

[1 2 3 4 5]


In [26]:
mat = np.array([[1,2,3], [4,5,6]])
print(mat)

[[1 2 3]
 [4 5 6]]


In [29]:
hello = tf.constant("Hello, TensorFlow!")


tf.print(hello)

Hello, TensorFlow!


In [35]:
node1= tf.constant(3.0, tf.float32)
node2= tf.constant(4.0)
#node3= tf.add(node1, node2)
node3= node1 + node2

In [36]:
print("node1:" , node1, "node2:", node2)
print("node3:" , node3)

node1: tf.Tensor(3.0, shape=(), dtype=float32) node2: tf.Tensor(4.0, shape=(), dtype=float32)
node3: tf.Tensor(7.0, shape=(), dtype=float32)


In [41]:
@tf.function
def forward() :
  return node1 + node2
out_a = forward()
print(out_a)


tf.Tensor(7.0, shape=(), dtype=float32)


In [57]:
W = tf.Variable(tf.ones(shape=(2,2)), name="W")
b = tf.Variable(tf.zeros(shape=(2)), name="b")

@tf.function
def forward(x):
  return W * x + b

out_a = forward([1,0])
print(out_a)

Tensor("StatefulPartitionedCall:0", shape=(2, 2), dtype=float32)


In [58]:
out_a = forward([3, 4])
print(out_a)

Tensor("StatefulPartitionedCall_1:0", shape=(2, 2), dtype=float32)


In [61]:
print(tf.add(9, 3))

Tensor("Add_4:0", shape=(), dtype=int32)
