<a href="https://colab.research.google.com/github/PJHSE/Learning/blob/main/20200205.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
pip install tensorflow

In [3]:
import tensorflow as tf 
tf.__version__

'2.7.0'

In [ ]:
pip install keras

In [13]:
import keras
keras.__version__

'2.7.0'

In [ ]:
pip install gensim

In [15]:
import gensim 
gensim.__version__

'3.6.0'

In [ ]:
pip install scikit-learn

In [17]:
import sklearn
sklearn.__version__

'1.0.2'

In [19]:
import nltk
nltk.__version__

'3.2.5'

In [ ]:
pip install konlpy

In [22]:
import konlpy
konlpy.__version__

'0.6.0'

In [24]:
import pandas as pd

In [26]:
sr = pd.Series([35000, 25000, 10000, 5000],index=['R석', 'S석', '일반석', '입석'])

print('표의 가격 :')
print('-'*20)
print(sr)

표의 가격 :
--------------------
R석     35000
S석     25000
일반석    10000
입석      5000
dtype: int64


In [29]:
print('표의 값(가격) :{}'.format(sr.values))
print('표의 종류(인덱스) :{}'.format(sr.index))

표의 값(가격) :[35000 25000 10000  5000]
표의 종류(인덱스) :Index(['R석', 'S석', '일반석', '입석'], dtype='object')


In [33]:
values = [[23.7, 12.2, 1.5],[13.9, 8.7, 7.5],[15.3, 5.0, 9.7] ]
index = ['orhodox center', 'point forward', 'Reading guard']
column = ['avp', 'avr', 'ava']

df = pd.DataFrame(values, index=index, columns=column)

print('3 선수의 평균 성적 : ')
print('-' *20)
print(df)

3 선수의 평균 성적 : 
--------------------
                 avp   avr  ava
orhodox center  23.7  12.2  1.5
point forward   13.9   8.7  7.5
Reading guard   15.3   5.0  9.7


In [37]:
print('3 선수의 포지션 : {}'.format(df.index))
print('3 선수가 갖는 3개의 지표 : {}'.format(df.columns))

3 선수의 포지션 : Index(['orhodox center', 'point forward', 'Reading guard'], dtype='object')
3 선수가 갖는 3개의 지표 : Index(['avp', 'avr', 'ava'], dtype='object')


In [39]:
data = [[23, 'Davis', 13.2],[30, 'Curry', 16.8], [1, 'Embiid', 16.5], [6, 'James', 14.9]]
df = pd.DataFrame(data)
print(df)

    0       1     2
0  23   Davis  13.2
1  30   Curry  16.8
2   1  Embiid  16.5
3   6   James  14.9


In [45]:
df=pd.DataFrame(data, columns = ['등번호','이름','승리 기여도' ], index = ['PowerForward', 'Point Guard', 'Center', 'Small Forward'])
#df=pd.DataFrame(data, index = ['PowerForward', 'Point Guard', 'Center', 'Small Forward'])

In [44]:
print(df)

   등번호      이름  승리 기여도
0   23   Davis    13.2
1   30   Curry    16.8
2    1  Embiid    16.5
3    6   James    14.9


In [46]:
data = {'등번호' : ['23', '30', '1', '6'],'이름':['Davis','Curry', 'Embiid', 'James'], '승리 기여도':[13.2, 16.8, 16.5, 14.9] }
df=pd.DataFrame(data)
print(df)

  등번호      이름  승리 기여도
0  23   Davis    13.2
1  30   Curry    16.8
2   1  Embiid    16.5
3   6   James    14.9


In [47]:
df.head(1)

등번호     이름  승리 기여도
0  23  Davis    13.2

In [48]:
df['등번호']

0    23
1    30
2     1
3     6
Name: 등번호, dtype: object

In [49]:
import numpy as np

In [50]:
list = np.array([1, 2, 3, 4, 5])

In [51]:
print(list)

[1 2 3 4 5]


In [57]:
mat = np.array([[1,2,3], [4,5,6]])
print(mat)

[[1 2 3]
 [4 5 6]]
